# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Brightbox Keel action'
description: "GitHub Action to notify a Keel webhook to deploy an tagged image"
author: 'Brightbox'
branding:
  color: 'green'
inputs:
  image:
    description: 'Docker image to trigger the webhook for'
    required: true
  hook-url:
    description: 'URL of the Keel native webhook to notify (including /v1/webhooks/native)'
    required: true
  tag:
    description: 'Tag of the image to notify Keel to deploy'
    required: true
  basic-auth-user:
    description: ''
    required: false
  basic-auth-password:
    description: ''
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
